const { withAppDelegate } = require('@expo/config-plugins');

// Registers HealthKit observer queries at launch, which is the one thing
// standing between Kairo and background delivery actually working.
//
// Apple requires observer queries to be registered in
// `application(_:didFinishLaunchingWithOptions:)` — before the JS bridge
// exists — for the app to be woken after it has been terminated. The library
// ships `BackgroundDeliveryManager.setupBackgroundObservers()` to do exactly
// that, but nothing calls it: `@kingstinct/react-native-healthkit`'s own Expo
// plugin runs only `withEntitlementsPlist` and `withInfoPlist`, and no pod code
// self-registers. So `background: true` grants the entitlement and the app
// still never wakes.
//
// `ios/` is regenerated by `expo prebuild --clean`, so this has to be a config
// plugin rather than a hand-edit to AppDelegate.swift.
//
// Calling this unconditionally on every launch is safe. `setupBackgroundObservers`
// bails out when HealthKit is unavailable, and reads the types to observe from
// UserDefaults — which are only written once JS has called
// `configureBackgroundTypes()` after the user granted permission. Before that it
// is a no-op, so this never triggers a permission prompt at launch.
// ## Why the Objective-C runtime instead of `import ReactNativeHealthkit`
//
// The obvious implementation — import the pod's Swift module and call
// `BackgroundDeliveryManager.shared.setupBackgroundObservers()` — does not
// compile. That module's umbrella header transitively pulls in NitroModules'
// C++ headers, and building it as an Objective-C module from a Swift file
// fails:
//
//     Null.hpp:8:10: error: 'functional' file not found
//     <unknown>:0: error: could not build Objective-C module 'NitroModules'
//
// Fixing that properly would mean enabling C++ interop across the whole app
// target, which is a large blast radius for one call at launch. The manager is
// `@objc public` with an `@objc public static let shared`, so it is reachable
// by selector without importing anything — `NSClassFromString` needs the
// module-qualified name because Swift classes carry it in the runtime.
//
// Deliberately reaching the *library's* manager rather than registering our own
// observers: its `pendingEvents` queue is what buffers changes that arrive
// before JS is ready, and `subscribeToChanges` drains it. Registering separate
// observers would leave the JS side never hearing about a background wake.
const CALL_MARKER = '// KAIRO: register HealthKit observer queries before the JS bridge exists';

const MANAGER_CLASS = 'ReactNativeHealthkit.BackgroundDeliveryManager';

function withHealthKitBackgroundObservers(config) {
  return withAppDelegate(config, (config) => {
    if (config.modResults.language !== 'swift') {
      throw new Error(
        `withHealthKitBackgroundObservers: expected a Swift AppDelegate, got ` +
          `"${config.modResults.language}". Expo generates Swift from SDK 54 on — ` +
          'if this changed, update plugins/withHealthKitBackgroundObservers.js.'
      );
    }

    let contents = config.modResults.contents;

    if (!contents.includes(CALL_MARKER)) {
      // Anchored on the `return super.application(...)` that closes
      // didFinishLaunchingWithOptions. The observers must be registered before
      // it returns, and this line is unique in the generated file.
      const returnAnchor =
        /([ \t]*)(return super\.application\(application, didFinishLaunchingWithOptions: launchOptions\))/;

      if (!returnAnchor.test(contents)) {
        throw new Error(
          'withHealthKitBackgroundObservers: could not find the ' +
            'didFinishLaunchingWithOptions return statement in AppDelegate.swift to ' +
            'anchor the observer registration. The Expo template may have changed — ' +
            'update plugins/withHealthKitBackgroundObservers.js.'
        );
      }

      const snippet =
        `${CALL_MARKER}\n` +
        `// Reached by selector rather than \`import ${MANAGER_CLASS.split('.')[0]}\`:\n` +
        `// that module's umbrella header pulls in NitroModules' C++ headers, which\n` +
        `// cannot be built as an Objective-C module from Swift. See\n` +
        `// plugins/withHealthKitBackgroundObservers.js.\n` +
        `if let managerClass = NSClassFromString("${MANAGER_CLASS}") as? NSObject.Type,\n` +
        `   let manager = managerClass.value(forKey: "shared") as? NSObject {\n` +
        `  manager.perform(NSSelectorFromString("setupBackgroundObservers"))\n` +
        `} else {\n` +
        `  // Loud rather than silent. An upstream rename would otherwise disable\n` +
        `  // background delivery with no symptom whatsoever.\n` +
        `  NSLog("[Kairo] HealthKit background observers NOT registered - ${MANAGER_CLASS} lookup failed.")\n` +
        `}`;

      contents = contents.replace(returnAnchor, (_m, indent, returnLine) => {
        const indented = snippet
          .split('\n')
          .map((line) => (line.length > 0 ? `${indent}${line}` : line))
          .join('\n');
        return `${indented}\n\n${indent}${returnLine}`;
      });
    }

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = withHealthKitBackgroundObservers;
