const { withPodfile } = require('expo/config-plugins');

// Two upstream CocoaPods podspec issues need a post_install fix rather than
// `inhibit_all_warnings!` below, because they aren't compiler warnings — they're
// Xcode build-phase diagnostics ("will run during every build"): Hermes's
// "Replace Hermes" script and react-native-healthkit's "Fix Swift 6.2" script
// both lack the `always_out_of_date` flag their sibling podspecs set (so Xcode
// can't tell they're deliberate, and warns). `ios/` is regenerated by
// `expo prebuild --clean`, so this has to be injected via a config plugin
// rather than hand-edited in ios/Podfile.
const POST_INSTALL_MARKER = '# KAIRO: suppress upstream CocoaPods script-phase warnings';

// The other ~1000 warnings in a Kairo build are ordinary compiler warnings
// (nullability, deprecated APIs, Sendable, unused functions, umbrella headers,
// etc.) scattered across dozens of vendored pods (React-Core, HealthKit,
// gesture-handler, Expo modules, ...) built against a newer/stricter toolchain
// than they were tested on. Patching each one individually isn't practical;
// `inhibit_all_warnings!` is the standard CocoaPods directive for exactly this —
// it silences warnings from pod (third-party) code while this app's own code
// (currently warning-free) still shows warnings normally.
const INHIBIT_MARKER = '# KAIRO: silence vendored pod compiler warnings';

function withIosBuildWarningFixes(config) {
  return withPodfile(config, (config) => {
    let contents = config.modResults.contents;

    if (!contents.includes(INHIBIT_MARKER)) {
      const targetAnchor = /\ntarget 'Kairo' do\n/;
      if (!targetAnchor.test(contents)) {
        throw new Error(
          "withIosBuildWarningFixes: could not find \"target 'Kairo' do\" in the " +
            'generated Podfile to insert inhibit_all_warnings!. The Expo Podfile ' +
            'template may have changed — update plugins/withIosBuildWarningFixes.js.'
        );
      }
      contents = contents.replace(
        targetAnchor,
        `\n${INHIBIT_MARKER}\ninhibit_all_warnings!\n\ntarget 'Kairo' do\n`
      );
    }

    if (!contents.includes(POST_INSTALL_MARKER)) {
      const snippet =
        `\n    ${POST_INSTALL_MARKER} (see plugins/withIosBuildWarningFixes.js)\n` +
        `    installer.pods_project.targets.each do |target|\n` +
        `      # inhibit_all_warnings! above doesn't reach every generated target\n` +
        `      # (e.g. the per-app 'Pods-Kairo' aggregate target) — force it directly\n` +
        `      # everywhere so nothing from vendored pod code leaks through.\n` +
        `      target.build_configurations.each do |bc|\n` +
        `        bc.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'\n` +
        `      end\n\n` +
        `      if target.name == 'hermes-engine'\n` +
        `        target.build_phases.each do |phase|\n` +
        `          if phase.respond_to?(:name) && phase.name.to_s.include?('Replace Hermes')\n` +
        `            phase.always_out_of_date = '1'\n` +
        `          end\n` +
        `        end\n` +
        `      end\n\n` +
        `      if target.name == 'ReactNativeHealthkit'\n` +
        `        target.build_phases.each do |phase|\n` +
        `          if phase.respond_to?(:name) && phase.name.to_s.include?('Fix Swift 6.2')\n` +
        `            phase.always_out_of_date = '1'\n` +
        `          end\n` +
        `        end\n` +
        `      end\n` +
        `    end\n`;

      // Anchor on the react_native_post_install(...) call's closing paren, which
      // sits alone on its own line in Expo's generated template — robust to its
      // keyword-argument list changing, but a future template reformat could
      // break this, so fail loudly rather than silently skipping the injection.
      const postInstallAnchor = /(react_native_post_install\([\s\S]*?\n\s*\))\n(\s*end\n)/;

      if (!postInstallAnchor.test(contents)) {
        throw new Error(
          'withIosBuildWarningFixes: could not find react_native_post_install(...) ' +
            'call in the generated Podfile to anchor the injected post_install code. ' +
            'The Expo Podfile template may have changed — update the anchor regex ' +
            'in plugins/withIosBuildWarningFixes.js.'
        );
      }

      contents = contents.replace(
        postInstallAnchor,
        (_m, call, closingEnd) => `${call}\n${snippet}\n${closingEnd}`
      );
    }

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = withIosBuildWarningFixes;
