const { withAppDelegate } = require('@expo/config-plugins');

// Registers HealthKit observer queries at launch, which is the one thing
// standing between Kairo and background delivery actually working.
//
// Apple requires observer queries to be registered in
// `application(_:didFinishLaunchingWithOptions:)` — before the JS bridge
// exists — for the app to be woken after it has been terminated. The library
// ships `BackgroundDeliveryManager.setupBackgroundObservers()` to do exactly
// that, but nothing calls it: `@kingstinct/react-native-healthkit`'s own Expo
// plugin runs only `withEntitlementsPlist` and `withInfoPlist`, and no pod code
// self-registers. So `background: true` grants the entitlement and the app
// still never wakes.
//
// `ios/` is regenerated by `expo prebuild --clean`, so this has to be a config
// plugin rather than a hand-edit to AppDelegate.swift.
//
// Calling this unconditionally on every launch is safe. `setupBackgroundObservers`
// bails out when HealthKit is unavailable, and reads the types to observe from
// UserDefaults — which are only written once JS has called
// `configureBackgroundTypes()` after the user granted permission. Before that it
// is a no-op, so this never triggers a permission prompt at launch.
const IMPORT_MARKER = '// KAIRO: HealthKit background observers';
const CALL_MARKER = '// KAIRO: register HealthKit observer queries before the JS bridge exists';

const HEALTHKIT_MODULE = 'ReactNativeHealthkit';

function withHealthKitBackgroundObservers(config) {
  return withAppDelegate(config, (config) => {
    if (config.modResults.language !== 'swift') {
      throw new Error(
        `withHealthKitBackgroundObservers: expected a Swift AppDelegate, got ` +
          `"${config.modResults.language}". Expo generates Swift from SDK 54 on — ` +
          'if this changed, update plugins/withHealthKitBackgroundObservers.js.'
      );
    }

    let contents = config.modResults.contents;

    if (!contents.includes(IMPORT_MARKER)) {
      // The block of imports at the very top of the file. Matching the block
      // rather than one known import keeps this working if Expo adds or
      // reorders imports in a future template.
      const importBlock = /^((?:(?:\w+ )?import [^\n]+\n)+)/;

      if (!importBlock.test(contents)) {
        throw new Error(
          'withHealthKitBackgroundObservers: could not find the import block at the ' +
            'top of AppDelegate.swift. The Expo template may have changed — update ' +
            'plugins/withHealthKitBackgroundObservers.js.'
        );
      }

      contents = contents.replace(
        importBlock,
        (_m, block) => `${block}${IMPORT_MARKER}\nimport ${HEALTHKIT_MODULE}\n`
      );
    }

    if (!contents.includes(CALL_MARKER)) {
      // Anchored on the `return super.application(...)` that closes
      // didFinishLaunchingWithOptions. The observers must be registered before
      // it returns, and this line is unique in the generated file.
      const returnAnchor =
        /([ \t]*)(return super\.application\(application, didFinishLaunchingWithOptions: launchOptions\))/;

      if (!returnAnchor.test(contents)) {
        throw new Error(
          'withHealthKitBackgroundObservers: could not find the ' +
            'didFinishLaunchingWithOptions return statement in AppDelegate.swift to ' +
            'anchor the observer registration. The Expo template may have changed — ' +
            'update plugins/withHealthKitBackgroundObservers.js.'
        );
      }

      contents = contents.replace(
        returnAnchor,
        (_m, indent, returnLine) =>
          `${indent}${CALL_MARKER}\n` +
          `${indent}BackgroundDeliveryManager.shared.setupBackgroundObservers()\n\n` +
          `${indent}${returnLine}`
      );
    }

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = withHealthKitBackgroundObservers;
